### PR TITLE
Issue #2918031: Replace copied css through sass imports

### PR DESCRIPTION
**Pull request by goldquest**

### CODE REVIEW

**Comment by mtodor** [comment]
From my point of view - ~2k lines removed - Looks GREAT!

**Comment by ol0lll** [comment]
PLEASE DO NOT SQUASH

**Comment by goldquest** [comment]
We have some comments from the analysing phase left, which might be irrelevant.
Mostly comments, which state, that something was removed with a `(todo)` at the end.
Could that be confusing for folks in the future?

**Comment by goldquest** [comment]
Looking good. 
The todos are actual todos, but don't change the visuals apparently. Might be issues with seven moving forward.

**Pull request merged**
