### PR TITLE
Issue #2934140: Missing development dependencies

### PR DESCRIPTION
**Pull request by ol0lll**

### CODE REVIEW

**Comment by webflo** [comment]
I think there is more stuff missing not just eslint.

**Comment by ol0lll** [comment]
@webflo Can you elaborate? I tested this on a fresh ubuntu vm and adding eslint seems to do the trick.

**Comment by webflo** [comment]
@ol0lll ``eslint-config-airbnb`` was missing. Afaik this package not a dependency of eslint and not listed in the package.json. It works in CI because its not used, but the DX is not great imo.

**Comment by mtodor** [comment]
@webflo I have changed that `.eslitrc` is root for this project. Anyway, it should not pick-up linting definitions from everywhere.

**Comment by ol0lll** [comment]
Tested on vanilla ubuntu, seems to be fine now.

**Pull request merged**
