### PR TITLE
Feature/ux entity browser

### PR DESCRIPTION
**Pull request by goldquest**
Styling of the entity browser

### CODE REVIEW

**Comment by chrfritsch** [comment]
And the styling of the overlay, which appears if you hover of an image, doesn't fit into the new design IMHO

**Comment by goldquest** [comment]
The "Import Images" issue was introduced, by having all `form-item__field-wrapper` be `display:flex`. It has to be investigated, if this styling has to be restricted / removed / changed.

**Comment by goldquest** [comment]
The other two issues are fixed

**Comment by goldquest** [comment]
Can't reproduce

**Pull request merged**
