### PR TITLE
Issue #3006166: Add a nicer select2 theme

### PR DESCRIPTION
**Pull request by ol0lll**

### CODE REVIEW

**Comment by chrfritsch** [comment]
bildschirmfoto 2018-10-16 um 10 53 47

Heights are not the same

**Comment by chrfritsch** [comment]
👍

**Comment by ol0lll** [comment]
https://projects.invisionapp.com/d/main#/console/9349346/214766307/preview

**Comment by chrfritsch** [comment]
bildschirmfoto 2018-10-17 um 13 54 43

Text and Arrow are not vertical aligned

**Comment by chrfritsch** [comment]
bildschirmfoto 2018-10-17 um 15 37 52

x and arrow are overlapping

**Pull request merged**
